"""Add image_filename to Property

Revision ID: 1e6f96280287
Revises: a29de3cbd1d4
Create Date: 2024-10-08 03:45:27.213738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6f96280287'
down_revision = 'a29de3cbd1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
