"""Added contact_number to Property

Revision ID: a29de3cbd1d4
Revises: 
Create Date: 2024-10-07 12:28:14.926400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29de3cbd1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=10), nullable=False))
        batch_op.drop_column('contact_phonenumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phonenumber', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
